"""add picture to purchases

Revision ID: 009f1b277bfc
Revises: a4a2cc7b3673
Create Date: 2025-12-05 19:52:54.888222

"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009f1b277bfc'
down_revision: str | None = 'a4a2cc7b3673'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_purchases_status'), ['status'], unique=False)
        batch_op.drop_column('is_completed')
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_purchases_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
