"""описание изменений

Revision ID: 679a594221d6
Revises: 009f1b277bfc
Create Date: 2025-12-05 21:12:58.528432

"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679a594221d6'
down_revision: str | None = '009f1b277bfc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_payment_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_provider'))
        batch_op.drop_column('provider')
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_payment_type'), ['payment_type'], unique=False)

    # ### end Alembic commands ###
