"""add priority field to requests

Revision ID: c9a61a404654
Revises: 0d0598f10bba
Create Date: 2025-12-06 03:15:20.409924

"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a61a404654'
down_revision: str | None = '0d0598f10bba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_next_run_time'))

    op.drop_table('jobs')
    
    # Создаем ENUM тип
    requestpriority = postgresql.ENUM('GENERAL', 'PREMIUM', name='requestpriority')
    requestpriority.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', requestpriority, nullable=False, server_default='GENERAL'))
        batch_op.create_index(batch_op.f('ix_requests_priority'), ['priority'], unique=False)
        batch_op.drop_column('attempts')
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_requests_priority'))
        batch_op.drop_column('priority')
    
    # Удаляем ENUM тип
    postgresql.ENUM(name='requestpriority').drop(op.get_bind(), checkfirst=True)

    op.create_table('jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_next_run_time'), ['next_run_time'], unique=False)

    # ### end Alembic commands ###
